#0-operating-system-concepts: 0-operating-system-concepts.c
#	$(CC) 0-operating-system-concepts.c -o 0-operating-system-concepts -Wall -Wextra -pedantic -std=c99
shell: shell.c
	$(CC) shell.c -o shell -Wall -Wextra -std=c99
