# sudoku_validator: sudoku_validator.c
# 	$(CC) sudoku_validator.c -o sudoku_validator -Wall -Wextra -std=c11 -lpthread

multithread_sorter: multithread_sorter.c
	$(CC) multithread_sorter.c -o multithread_sorter -Wall -Wextra -std=c11 -lpthread